### ISSUE TITLE
separate tabs for tweets by that handle and tweets by others

### ISSUE THREAD

**Issue by libbyh** [casmlab/stack#11]
We talked about this at the lab meeting Friday, and I just wanted to get it written down.

IF 
Twitter API call is type **track**

THEN
When a user clicks the handle in the controller detail page, the view that pops up should have two tabs: "View [handle]'s tweets" and "View replies and RTs"

These tabs shouldn't appear for **follow** collectors because they contain different results. See the API docs about [follow](https://dev.twitter.com/streaming/overview/request-parameters#follow) and [track](https://dev.twitter.com/streaming/overview/request-parameters#track) calls.

**Comment by pratik27shah** [comment]
Done partially and for final completion firstly the issue 12 needs to be solved,updated code for track,need to handle the follow case

**Comment by pratik27shah** [comment]
even for API Filter follow data is present in both the cases "View [handle]'s tweets" and "View replies and RTs"

**Comment by libbyh** [comment]
Titles of those tabs should be as described above 

- View [handle]'s tweets
- View replies and RTs (from [follow](https://dev.twitter.com/streaming/overview/request-parameters#follow))
- View mentions (from [track](https://dev.twitter.com/streaming/overview/request-parameters#track))
