### ISSUE TITLE
tweets should display in reverse chronological order

### ISSUE THREAD

**Issue by libbyh** [casmlab/stack#13]
Default display for tweets should be reverse chronological. Option for "sort chronologically" should be available.

**Comment by pratik27shah** [comment]
means latest tweets on the top.
currently,it is like the oldest tweets are on the top

**Comment by libbyh** [comment]
Right, default should be newest first.

**Comment by pratik27shah** [comment]
should data duplication be handled?,because their are same tweets.present in the DB,leading to ambiguity,because the fix to display in reverse has been committed

**Comment by libbyh** [comment]
Do the tweets have unique IDs? Some accounts post the same tweet more than once by accident or by design. I'm not worried about duplicates right now but something to flag for review later.

**Comment by pratik27shah** [comment]
Refer #16 for duplicates
