### ISSUE TITLE
Dedupe database script

### ISSUE THREAD

**Issue by libbyh** [casmlab/stack#16]
Twitter's "follow" and "track" API filters return two copies of replies. So, we should have a script that runs regularly to dedupe the database. It should make sure there are unique 'id_str'.

**Comment by jhemsley** [comment]
Really? Do you mean if you use both at the same time going into the same db, or do you mean if just run a follow you get dup replies? Always, or just sometimes?

By the way, when you index with mongo you can tell it to drop dups and it will do it for you.

**Comment by libbyh** [comment]
Yeah, when you run both into the same database you get dupes - e.g.,
"follow" realDonaldTrump and "track" realDonaldTrump show 2 copies of
replies

**Comment by jhemsley** [comment]
Got it. Yeah, that makes sense. Yeah, we periodically index on id_str with drop dups to fix dup problems. You do get dups 'naturally' sometimes even with just one collector. Twitter api has some minor bugs it seems.

**Comment by libbyh** [comment]
Drop dups isn't available in mongo 3.0+, so we're trying [something like](https://stackoverflow.com/questions/4010032/too-much-data-duplication-in-mongodb)

1. Create collection dump with mongodump
3. Clear collection
5. Add unique index
7. Restore collection with mongorestore

**Comment by pratik27shah** [comment]
db.tweets.aggregate({$group:{_id:{id_str:"$id_str"},count:{$sum:1},docs:{$push:"$_id"}}},{$match:{count:{$gt:1}}})   returns all duplicates having more then one time the same id_Str(tweet id) to find duplicates in mongodb

**Comment by pratik27shah** [comment]
implemented for rogue,potus,mil,the backup of theses databases is stored in mnt/stack2/dbbackup282017,
works fine all duplicates are removed
