### ISSUE TITLE
disable "track" collector detail page popups

### ISSUE THREAD

**Issue by libbyh** [casmlab/stack#17]
Until we get the "track" collectors figured out (see #9), disable the popup features for collectors of that type.

**Comment by pratik27shah** [comment]
done

**Comment by pratik27shah** [comment]
{% if collector['api']== "track" %}
					 <td   id={{term['id']}} names={{term['term']}} >{{ term['term'] }}</td>
				 {% else %}
					<td  class="termname" id={{term['id']}} names={{term['term']}} onclick="ShowContent(this.id)">{{ term['term'] }}</td>
				{% endif %}

just  replace the else-if in the code by <td  class="termname" id={{term['id']}} names={{term['term']}} onclick="ShowContent(this.id)">{{ term['term'] }}</td> to make it work for track in future
