### ISSUE TITLE
Time stamp on tweets in view

### ISSUE THREAD

**Issue by libbyh** [casmlab/stack#21]
For both "tweets by" and "replies" by, add a time stamp (at least day) so we can see when they were posted.

<img width="1502" alt="screen shot 2017-06-09 at 5 51 38 pm" src="https://user-images.githubusercontent.com/182478/26997054-500a1712-4d3c-11e7-9c92-5b6718e2b5e9.png">

**Comment by pratik27shah** [comment]
Posted On:2017-04-20 19:33:46 time stamp has been added
