### ISSUE TITLE
Fix spacing in tweets view

### ISSUE THREAD

**Issue by libbyh** [casmlab/stack#22]
Sometimes there's a space after the colon, sometimes not. Get all these stats lined up.

<img width="1502" alt="screen shot 2017-06-09 at 5 51 38 pm" src="https://user-images.githubusercontent.com/182478/26997140-dc041876-4d3c-11e7-97fb-d306e9cf4b46.png">

**Comment by pratik27shah** [comment]
to fix this tweets have been trimmed

**Comment by pratik27shah** [comment]
done
