### ISSUE TITLE
WSGI Error in views

### ISSUE THREAD

**Issue by libbyh** [casmlab/stack#5]
Many entries like this in the Apache error log:

`[Thu Mar 23 15:28:54.850866 2017] [wsgi:error] [pid 9473] Traceback (most recent call last):
[Thu Mar 23 15:28:54.850873 2017] [wsgi:error] [pid 9473]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
[Thu Mar 23 15:28:54.850878 2017] [wsgi:error] [pid 9473]     response = self.full_dispatch_request()
[Thu Mar 23 15:28:54.850883 2017] [wsgi:error] [pid 9473]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
[Thu Mar 23 15:28:54.850888 2017] [wsgi:error] [pid 9473]     rv = self.handle_user_exception(e)
[Thu Mar 23 15:28:54.850892 2017] [wsgi:error] [pid 9473]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
[Thu Mar 23 15:28:54.850897 2017] [wsgi:error] [pid 9473]     reraise(exc_type, exc_value, tb)
[Thu Mar 23 15:28:54.850902 2017] [wsgi:error] [pid 9473]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
[Thu Mar 23 15:28:54.850906 2017] [wsgi:error] [pid 9473]     rv = self.dispatch_request()
[Thu Mar 23 15:28:54.850911 2017] [wsgi:error] [pid 9473]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
[Thu Mar 23 15:28:54.850916 2017] [wsgi:error] [pid 9473]     return self.view_functions[rule.endpoint](**req.view_args)
[Thu Mar 23 15:28:54.850920 2017] [wsgi:error] [pid 9473]   File "/mnt/stor2/stack/app/decorators.py", line 41, in decorated_function
[Thu Mar 23 15:28:54.850925 2017] [wsgi:error] [pid 9473]     return f(*args, **kwargs)
[Thu Mar 23 15:28:54.850929 2017] [wsgi:error] [pid 9473]   File "/mnt/stor2/stack/app/decorators.py", line 56, in decorated_function
[Thu Mar 23 15:28:54.850934 2017] [wsgi:error] [pid 9473]     return f(*args, **kwargs)
[Thu Mar 23 15:28:54.850938 2017] [wsgi:error] [pid 9473]   File "/mnt/stor2/stack/app/decorators.py", line 15, in decorated_function
[Thu Mar 23 15:28:54.850943 2017] [wsgi:error] [pid 9473]     return f(*args, **kwargs)
[Thu Mar 23 15:28:54.850948 2017] [wsgi:error] [pid 9473]   File "/mnt/stor2/stack/app/views.py", line 256, in network_home
[Thu Mar 23 15:28:54.850952 2017] [wsgi:error] [pid 9473]     resp = db.check_process_status(g.project['project_id'], 'process', module=network)
[Thu Mar 23 15:28:54.850957 2017] [wsgi:error] [pid 9473]   File "/mnt/stor2/stack/app/models.py", line 638, in check_process_status
[Thu Mar 23 15:28:54.850962 2017] [wsgi:error] [pid 9473]     active = network_mod['processor_active']
[Thu Mar 23 15:28:54.850966 2017] [wsgi:error] [pid 9473] TypeError: 'NoneType' object has no attribute '__getitem__'`

**Comment by pratik27shah** [comment]
issue fixed,and code commited it was a bootstrap file missing issue..which has been resolved

**Comment by pratik27shah** [comment]
please delete the errror.log file and restart the server issue should not occur now...
