### ISSUE TITLE
Create MongoDB indices at DB creation

### ISSUE THREAD

**Issue by libbyh** [casmlab/stack#6]
DBs need indices to make retrieval easier/faster.

# Example

## For user id

`db.tweets.createIndex( { user.id : 1 } , { background: true } )`

More info here: https://docs.mongodb.com/v3.2/core/index-creation/

As of 3/24/17, Beckett is running MongoDB 3.2.

**Comment by pratik27shah** [comment]
indices have been created by code for data retrieval of users...so for example if a collector items does not have indexes and user  clicks on the term the first thing that happens is index creation ..
![index](https://cloud.githubusercontent.com/assets/17016381/24319354/8bd32aae-10e7-11e7-8c24-23c275b1b99d.PNG)
