### ISSUE TITLE
Term summary stats

### ISSUE THREAD

**Issue by libbyh** [casmlab/stack#8]
For each term, display the following info:

1.	Total number of Tweets per day, per week, per month
              -can we track time of the day tweets?
2.	Number of tweets that have photographs
3.	Number of tweets that have videos
4.	Number of tweets with hashtags
5.	Number of tweets that are RTs of other tweets
7.	Number of tweets with exclamation point!
8.	Number of tweets using ALL CAPS for some words
1. Number of tweets with profanity
11.	How many followers over time

**Comment by pratik27shah** [comment]
Total URLS:
Total Tweets with Hashtags:
Total Tweets with exclamation :
Total Tweets with User mentions :
Total Tweets with Re-tweeted :
this values are being displayed now...

**Comment by pratik27shah** [comment]
Total URLS:
Total Tweets with Hashtags:
Total Tweets with exclamation :
Total Tweets with User mentions :
Total Tweets with Re-tweeted :
this values are being displayed now... is this ok??

**Comment by pratik27shah** [comment]
working on the feature for faster lookup in case when there is alot of data

**Comment by libbyh** [comment]
These look ok. We're missing a "Total tweets in database" count - that was my oversight. Also, how does user get back to this view once a user clicks "View Content"?

**Comment by libbyh** [comment]
These don't show up for terms in the potus45 collector. Is it just that there are millions of tweets taking too long?

**Comment by libbyh** [comment]
Figured out the problem - it's calculating all these stats for every tweet in the collector and should calculate for just those tweets authored by the "term".

**Comment by pratik27shah** [comment]
as per discussion
